name: crypto_exchange
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^13.2.0
  google_fonts: ^6.1.0
  flutter_bloc: ^8.1.4
  flutter_svg: ^2.0.9
  cupertino_icons: ^1.0.6
  easy_localization: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/translations/
    - assets/svg/

  fonts:
    - family: Lato
      fonts:
        - asset: assets/font/Lato-Regular.ttf
        